
ALTER TABLE user_anime_list 
ADD COLUMN IF NOT EXISTS start_date TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS finish_date TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS rewatch_count INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS favorite BOOLEAN NOT NULL DEFAULT false; 