-- Create carousel_slides table
CREATE TABLE carousel_slides (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    button_text VARCHAR(100) NOT NULL,
    image_url TEXT NOT NULL,
    order_index INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Create news table
CREATE TABLE news (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    full_content TEXT NOT NULL,
    date DATE NOT NULL,
    image_url TEXT,
    link_slug VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Create blog_posts table
CREATE TABLE blog_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    author VARCHAR(100) NOT NULL,
    date DATE NOT NULL,
    image_url TEXT,
    category VARCHAR(50) NOT NULL CHECK (category IN ('blog', 'review')),
    rating DECIMAL(3,1) CHECK (rating >= 0 AND rating <= 10),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Create trigger function for updating updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = TIMEZONE('utc'::text, NOW());
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Create triggers for all tables
CREATE TRIGGER update_carousel_slides_updated_at
    BEFORE UPDATE ON carousel_slides
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_news_updated_at
    BEFORE UPDATE ON news
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_blog_posts_updated_at
    BEFORE UPDATE ON blog_posts
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Insert initial data for carousel slides
INSERT INTO carousel_slides (title, description, button_text, image_url, order_index) VALUES
('Demon Slayer', 'Follow Tanjiro''s journey as he seeks to turn his sister back into a human and avenge his family.', 'Watch Now', '/images/demon-slayer.jpg', 1),
('One Piece', 'Join Luffy and his crew on their epic adventure to find the legendary treasure, One Piece.', 'Start Adventure', '/images/one-piece.jpg', 2);

-- Insert initial data for news
INSERT INTO news (title, description, date, image_url, link_slug) VALUES
('Jujutsu Kaisen Season 2 Finale', 'The epic conclusion to the Shibuya Incident arc brings unexpected twists and emotional moments that will leave fans speechless.', '2024-01-13', '/images/jjk.jpg', 'jjk-finale'),
('Demon Slayer Season 4 Announced', 'The Hashira Training Arc is officially confirmed for 2024. Get ready for intense training sequences and epic battles.', '2024-01-12', '/images/demon-slayer-news.jpg', 'demon-slayer-s4');

-- Insert initial data for blog posts
INSERT INTO blog_posts (title, content, author, date, image_url, category) VALUES
('Top 10 Anime of 2023', 'Our picks for the best anime series of the year...', 'AnimeExpert', '2023-12-31', '/images/top-10.jpg', 'blog');

INSERT INTO blog_posts (title, content, author, date, image_url, category, rating) VALUES
('Attack on Titan Finale Review', 'A masterful conclusion to an epic series...', 'CriticPro', '2023-11-05', '/images/aot.jpg', 'review', 9.5); 